services:
  - type: web
    name: lapvision
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
    disk:
      name: lapvision-uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 2